name: Deploy to GitHub Pages
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
        npm uninstall eslint-plugin-vue
        npm install eslint-plugin-vue@9.33.0 --save-dev
        npm install --legacy-peer-deps && npm run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist