name: deploy website

on: 
  push: 
    branches: [ main ]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
      - uses: actions/checkout@v3

      - name: set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install dependencies
        run: npm install

      - name: build app
        run: npm run build

      - name: deploy app
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist
