name: deploy website

on: 
  push: 
    branches: [ main ]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: install nodejs
      - uses: actions/checkout@v3

      - name: install deps
        run: npm install

      - name: build app
        run: npm run build

      - name: deploy app
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist
